[project]
name = "E-commerce-Customer-Service-for-order-management-with-AG2"
version = "0.1.0"
description = "E commerce Customer Service for Order Management with AG2"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ag2[openai]>=0.9.9",
]
