[project]
name = "AG2-Agent-Pattern-Cookbook"
version = "0.1.0"
description = "AG2 Agent Pattern Cookbook"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ag2[openai]>=0.9.9",
]
